### ISSUE TITLE
Error al no encontrar carpeta temporal

### ISSUE THREAD

**Issue by ChopChopKodi** [tvalacarta/pelisalacarta#396]
En un Android TVBox me ha dado un error bastante raro en mct.py diciendo que la function mkdtemp() ha fallado porque no encuentra una carpeta temporal donde escribir.
Por lo que he leido Android no tiene carpeta temporal global como cualquier Unix, y el fallo ese parece un fallo de la compilación/configuración de Python de Kodi que tendría que escribir en una carpeta temporal dentro de la carpeta de la aplicación.

Yo lo he arreglado a las bravas accediendo como root y creando una carpeta /tmp, pero supongo que habría que "bypasear" el problema desde mct.py para que funcione sin tener que tocar nada como root.

En este enlace https://github.com/alanjds/python-for-android/commit/2efeee1dac5f62e1e617a3cb027deb362cd6df7c he encontrado un código que podría servir como base para un posible arreglo.

```
16:35:18 T:18446744072300250712  NOTICE:     [launcher.run] pelisalacarta.platformcode.launcher Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.pelisalacarta/platformcode/launcher.py", line 192, in run                                                xbmctools.play_video(item)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.pelisalacarta/platformcode/xbmctools.py", line 562, in play_video
                                                mct.play( mediaurl, xbmcgui.ListItem("", iconImage=item.thumbnail, thumbnailImage=item.thumbnail), subtitle=item.subtitle )
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.pelisalacarta/platformcode/mct.py", line 133, in play
                                                tempdir = tempfile.mkdtemp()
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/tempfile.py", line 310, in mkdtemp
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/tempfile.py", line 254, in gettempdir                         File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/tempfile.py", line 201, in _get_default_tempdir
                                            IOError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']
```

**Comment by r0balo** [comment]
Esto es nuevo :) Quizás lo mejor sería usar la misma carpeta de los torrents para el archivo temporal ya que es la primera noticia que tengo de que falle en android
```
    # -- magnet2torrent -----------------------------------------
    if torrent_file.startswith("magnet"):
        #tempdir = tempfile.mkdtemp()
        tempdir = os.path.join( save_path_torrents , "temp" )
        if not os.path.exists(temp): os.mkdir(temp)
```
Eso creo que debería funcionar y no necesitaría tener que crear la carpeta manualmente

**Comment by ChopChopKodi** [comment]
Yo me he quedado tonto cuando he visto el error. El fallo es algo que está mal en el Python para Android que usan en Kodi, aunque tengo puesta la última 16.1 Jarvis del Google Play, pero como no creo que arreglen esa versión habrá que tenerlo en cuenta. Igual en la siguiente lo arreglan y no es necesario o sólo pasa en determinadas marcas

El arreglo que propones aunque ahora mismo funcionaría, no sé si es válido a largo plazo. Creo que se hablaba hace un tiempo de usar los diálogos de Kodi para seleccionar las carpetas de _download_ y creo que las funciones de Kodi soportan carpetas en remoto de forma transparente, así que la ruta esa puede que en determinados caso no sea una carpeta local sino una URL o similar. Tampoco sé si libtorrent está preparado para ello.

Bueno, sin irme a un futuro alternativo, el arreglo temporal parece tan fácil como hacer lo que propones

**Comment by tvalacarta** [comment]
Yo veo que el arreglo está bien en cualquier caso, aunque con un try-except al hacer el mkdtemp y si falla creamos el directorio temporal en la ruta de descarga de los torrents.

**Comment by r0balo** [comment]
@tvalacarta 
Pues sí, esa sería una buena solución
@ChopChopKodi 
Si somos capaces de montar unidades de red en android no deberíamos tener problemas con los recursos compartidos pero si usamos smb tengo mis dudas que funcione aún no cerrando la conexión con el recurso. La teoría es que sí debería funcionar al igual que funciona cuando copiamos archivos usando el mismo protocolo. Tendríamos que modificar la librería libsmb que usamos y probar.
