### ISSUE TITLE
Modificar las dependencias de urllib, urllib2 para usar "requests"

### ISSUE THREAD

**Issue by SeiTaN80** [tvalacarta/pelisalacarta#42]
Hola,

A colación lo que dijo @neno1978 de usar las librerias de requests, he visto que se podría usar para realizar scrapper y jubilar las anteriores librerías usadas urllib y urllib2.

No haría falta incluirla dentro del addon, sino que añadiendo la dependencia en `addon.xml` ya funcionaría.

```
<requires>
    <import addon="xbmc.python" version="2.1.0"/>
    **<import addon="script.module.requests" version="x.x.x"/>**
</requires>
```

A ver que opina Jesús, un saludo.

**Comment by r0balo** [comment]
Seitan, esto es una cosa que nunca he comprado, tanto como requests, simplejson y unidecode están incluido en la instalación de kodi o las incluye otro plugin?
Digo esto porque si no viene instalada por defecto, tendríamos que hacerlo nosotros.
No es mala idea hacerlo como dices, yo tengo problemas con la versión que tengo de requests con util.default_user_agent() y lo tengo corregido pero en la del módulo de librerías de Add-ons ya está corregido.
De la forma que comentas dispondríamos de la ultima actualización de una forma bastante comoda

**Comment by SeiTaN80** [comment]
Yo lo he probado y si funciona, en mi kodi tengo ese módulo.

Habría que probar instalando kodi de cero y ver si se baja solo al instalar el addon de `pelisalacarta`.

Y si, es muy cómodo, aligeras el addon de peso y como comentas tienes la última versión en un momento.

Ya para otros sistemas como Plex habría que estudiar como va, si se puede obtener fácilmente como un import o hay que añadirlo como se hace con las librerias actualmente.

**Comment by tvalacarta** [comment]
Efectivamente, si lo declaras como dependencia en el addon.xml lo instala automáticamente siempre que ese módulo esté disponible en alguno de los repositorios que tengas instalado.

No obstante el objetivo de que estén esas librerías dentro del proyecto es precisamente todas las plataformas que no son Kodi, incluyendo los XBMC viejos y el resto de sistemas.

Si descubres que uno de los módulos está obsoleto como comenta @r0balo, pues lo actualizamos en el directorio "lib" y listo :)

**Comment by SeiTaN80** [comment]
Jesús venia a confirmar precisamente eso, he probado a instalar el addon de pelisalacarta con addon.xml modificado y me descarga automáticamente la librería.

¿No habría una manera de personalizar los builds que haces para evitar precisamente lo que has dicho?
Si la versión es <= isengard que se incluyan las librerias tal dentro del zip, y sino pues se usa el import, como las referencias al import es al mismo sitio no habría ningún problema.

Y ya a partir de una versión empezar de cero o usando mejoras que permitan que el código sea más legible y actualizable, y las antiguas que se solucionen bugs o actualizar solo canales y servers.

**Comment by SeiTaN80** [comment]
He estado dandole vueltas y quizás el mejor resultado sería crear un scrapertoolsv2.py, que mejore el actual, añadiendo o eliminando funciones, asi se podría cambiar las referencias de urllib2 por las requests y dejar el codigo compacto como está ahora.

**Comment by tvalacarta** [comment]
Acabo de abrir un issue, porque he visto que animeflv no funciona en Boxee debido a un problema entre la sintaxis que tiene Requests y la versión del intérprete de Python que tiene Boxee.

Realmente ¿para qué tenemos que usar requests? ¿hay algo que no se pueda hacer con las funciones basadas en urllib?

**Comment by SeiTaN80** [comment]
Yo he visto mejoras en temas de rendimiento, aparte que es más cómodo para saber si hay un error al cargar la pagina.
Si se quisiera hacer lo mismo con el modo actual, tendríamos que hacer una función para que haga el scraper del codigo de error de la página.

**Comment by neno1978** [comment]
Para nada realmente yo lo hice solo para bricocine porque da muchos fallos de la otra manera q resquet no los da , pero si crea más conflicto q otra cosa pues se elimina y punto. Vuelvo en brico a lo normal y si falla aveces pues q falle .

**Comment by tvalacarta** [comment]
No hace falta que toquemos nada de momento, tampoco es muy crítico.

Creo que una solución podría ser hacer un poco más elegante el actual scrapertools (se notan las horas de privación de sueño en ese código) para que podamos usarlo más cómodamente.

Quitaré todo el rollo de las caches, que realmente nunca llegó a ser muy útil, y haré algo más parecido a lo que tenemos en plugintools.

https://github.com/tvalacarta/pelisalacarta/blob/master/python/main-ui/plugintools.py

@neno1978, me preocupa un poco lo que comentas de esos fallos que da el actual scrapertools y que no ocurren con requests. ¿Puedes darme algún detalle, o cómo reproducirlo?

Tomo nota del código de error de la página :)

**Comment by neno1978** [comment]
Pues creo recordar  q da pagina no encontrada y resquet si la trinca, y Ayer me do cuenta q si te vas a Bricocine series, blacklist cap 7 temp 3 en info cap el resquet falla y el otro no, osea que yo creo q si crea más conflicto q otra cosa pues se elimina y punto. Vuelvo en brico a lo normal y si falla aveces pues q falle .

**Comment by neno1978** [comment]
X cierto ahora no lo puedo poner exactamente el motivo xq no estoy en casa,pero yo no puedo actualizar me da error , algo parecido a que remote no sé que no está definido, después lo miro y lo pongo igual solo es cosa mía ;)

**Comment by r0balo** [comment]
El motivo de usar Requests en algun canal era por las proteciones de las web ante ataques.
Nuestro amigo italiano @DrZ3r0 soluciona este problema sin usar Requests. Sería cuestión de mirar si coincide con los mismo casos que se nos dieron. Me suena que sí. Lo que hace es esperar los segundos que vienen fijados en la respuesta del header y redireccionar.

**Comment by tvalacarta** [comment]
@neno1978 Cuando puedas mira a ver si me puedes contar el problema al actualizar...
Creo que subiré una actualización para arreglar las dos o tres cosillas que han salido mal.

**Comment by neno1978** [comment]
sorry jesus, he tenido un domingo movidito, mañana o miraré mas a fondo pero esto es lo que pasa ;
 Traceback (most recent call last):
                                              File "/Users/ignaciobernal/Library/Application Support/Kodi/addons/plugin.video.pelisalacarta/default.py", line 27, in <module>
                                                launcher.run()
                                              File "/Users/ignaciobernal/Library/Application Support/Kodi/addons/plugin.video.pelisalacarta/platformcode/launcher.py", line 54, in run
                                                updater.update(params)
                                              File "/Users/ignaciobernal/Library/Application Support/Kodi/addons/plugin.video.pelisalacarta/core/updater.py", line 198, in update
                                                remotefilename = REMOTE_FILE+params.get("version")+".zip"
                                            NameError: global name 'REMOTE_FILE' is not defined

**Comment by tvalacarta** [comment]
¿Qué versión tenías instalada?

¿Puedes decirme qué plataforma tienes en "core/config.py" en la línea 18?

    PLATFORM_NAME = "kodi-isengard"

**Comment by neno1978** [comment]
Por las barbas de Gandalf!! XBMC-FRODOOOOOOOORRR ... Que relio habré hecho ... 😵😵

**Comment by tvalacarta** [comment]
Ok, ya veo el problema entonces :)

Gracias je je je

**Comment by neno1978** [comment]
Omeeee!! Pero no me dejes "asin" !! Que hago ? Lo cambio por kodi-isegard?? ;)

**Comment by tvalacarta** [comment]
Depende de la versión que tengas realmente :)

El problema es que las actualizaciones nunca cambian la versión de Kodi, así que si te instalaste Frodo y luego has ido actualizando sigues usando la misma versión.

Hay poca diferencia de una a otra, hago un ZIP para que la gente no se líe con qué versión instalar.

Lo más fácil es que instales la nueva versión a mano, descarga el ZIP en el directorio "addons", lo descomprimes y listo.

El fallo está en el updater, las versiones de xbmc están como "xbmcfrodo" en lugar de "xbmc-frodo". Así que el updater no sabe qué versión tienes.

**Comment by neno1978** [comment]
Ok jefe , eso haré ;)
