### ISSUE TITLE
Errores que veo en el log

### ISSUE THREAD

**Issue by Palatosino** [tvalacarta/pelisalacarta#714]
Revisando el log me encuentro con estos errores, no se ni como los han llegado a ellos, pero bueno, yo lo informo, ya que ayer se me quejaron de que no iban varios canales:

```
17:23:26.197 T:1406366704  NOTICE: pelisalacarta.core.servertools [get_server_parameters] Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.pelisalacarta/core/servertools.py", line 321, in get_server_parameters
                                                JSONFile =  xml2dict(os.path.join(config.get_runtime_path(),"servers", server + ".xml"))["server"]
                                            KeyError: 'server'
17:23:26.198 T:1406366704  NOTICE: pelisalacarta.core.servertools [is_server_enabled] Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.pelisalacarta/core/servertools.py", line 300, in is_server_enabled
                                                if server_parameters["active"] == "true":
                                            KeyError: 'active'
```
Y no sale pocas veces:
Me los he encontrado varias veces:
osmc@osmc:~$ grep "KeyError: 'server'" ~/.kodi/temp/kodi.log | wc -l
126

A lo mejor no es nada, pero ahí está.

También encuentro cada mañana, al llamar al updatebiblio, que me sale esto:

```
09:00:01.682 T:1958904752 WARNING: RunScript called for a non-script addon 'plugin.video.pelisalacarta'. This behaviour is deprecated.
09:00:02.542 T:1370711024  NOTICE: pelisalacarta.default init...
09:00:03.226 T:1370711024  NOTICE: pelisalacarta.core.jsontools Probando json incluido en el interprete
09:00:03.788 T:1370711024  NOTICE: pelisalacarta.core.httptools [load_cookies] Leyendo fichero cookies
09:00:04.080 T:1370711024  NOTICE: pelisalacarta.platformcode.launcher.run
09:00:04.081 T:1370711024   ERROR: ######## ERROR #########
09:00:04.081 T:1370711024   ERROR:     [pelisalacarta.core.jsontools.load_json] **NO** se ha podido cargar el JSON
09:00:04.085 T:1370711024   ERROR: ######## ERROR #########
09:00:04.085 T:1370711024   ERROR:     [pelisalacarta.core.jsontools.load_json] Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.pelisalacarta/core/jsontools.py", line 58, in load_json
                                                value = json.loads(*args, **kwargs)
                                              File "/usr/lib/python2.7/json/__init__.py", line 351, in loads
                                                return cls(encoding=encoding, **kw).decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
09:00:04.087 T:1370711024  NOTICE: pelisalacarta.platformcode.launcher [run] action= 'update_biblio', channel= 'biblioteca', infoLabels= {}
... continúa el update biblio OK, pero ahí está el traceback
```

Por último, también me sale este traceback, creo que es cuando se llama al findvideos, que va probando
```
18:19:34.795 T:1355609072  NOTICE: pelisalacarta.servers.oboom [find_videos] [oboom.py] find_videos #(oboom.com/[a-zA-Z0-9]+)#
18:19:34.803 T:1355609072  NOTICE: pelisalacarta.servers.flashx find_videos #flashx.(?:tv|pw)/(?:embed.php\?c=|embed-|playvid-|)([A-z0-9]+)#
18:19:34.817 T:1355609072  NOTICE: pelisalacarta.servers.cnubis find_videos #cnubis.com/plugins/mediaplayer/(.*?/[^.]+.php\?u\=[A-Za-z0-9]+)#
18:19:34.822 T:1355609072  NOTICE: pelisalacarta.core.servertools [findvideos] Error en el conector #safelinking#
18:19:34.822 T:1355609072  NOTICE: pelisalacarta.core.servertools [findvideos] Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.pelisalacarta/core/servertools.py", line 127, in findvideos
                                                result = server_module.find_videos(data)
                                            AttributeError: 'module' object has no attribute 'find_videos'
18:19:34.830 T:1355609072  NOTICE: pelisalacarta.servers.thevideos [find_videos] #thevideos.tv/(?:embed-|)([a-z0-9A-Z]+)#
18:19:34.840 T:1355609072  NOTICE: pelisalacarta.servers.firedrive [find_videos] [firedrive.py] find_videos #(?:firedrive|putlocker).php\?url=([A-Z0-9]+)#
18:19:34.844 T:1355609072  NOTICE: pelisalacarta.servers.firedrive [find_videos] [firedrive.py] find_videos #(?:firedrive|putlocker).com/(?:file|embed)/([A-Z0-9]+
```

**Comment by SeiTaN** [comment]
El primer error que dices es debido a que no encuentra el servidor, está dentro de un try/catch, si le paso a servertools por ejemplo... un servidor con el nombre "opinlead", da ese error, ya que intenta importar con ese nombre y no existe.

Quizás se podría poner más bonito y explicativo, pero es eso.

El segundo parece como bien dices que al leer un fichero json está dando fallos, ya puede ser por el formato o que se ha guardado con encoding incorrecto/mezclado anteriormente.

El tercero, no deberia de darte, safelinking está en otra carpeta que no es server, así que puede ser dos cosas:
1) que no tengas los ficheros actualizados.
2) que el canal le pasa directamente safelink a servertools cuando no debería ser (servertools no está preparado para eso).
